default:
    image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
    - debug
    - release
    - test

build:
    stage: debug
    script:
        - apt-get update && apt-get install -y fontconfig
        - mkdir -p /usr/share/fonts/truetype/paintdrops
        - cp /builds/dawson-csy3-24-25/510/section2/Sood/paintdrops/Arial_Bold.ttf /usr/share/fonts/truetype/paintdrops/
        - fc-cache -fv
        - dotnet build -c debug

release:
    stage: release
    script:
        - apt-get update && apt-get install -y fontconfig
        - mkdir -p /usr/share/fonts/truetype/paintdrops
        - cp /builds/dawson-csy3-24-25/510/section2/Sood/paintdrops/Arial_Bold.ttf /usr/share/fonts/truetype/paintdrops/
        - fc-cache -fv
        - dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --no-self-contained 
        - cd /builds/dawson-csy3-24-25/510/section2/Sood/paintdrops/PaintDrops/bin/Release/net6.0/win-x64
        - mv ./publish /builds/dawson-csy3-24-25/510/section2/Sood/paintdrops
        - cd /builds/dawson-csy3-24-25/510/section2/Sood/paintdrops
        - tar -czvf GameFiles.tar ./publish
    artifacts:
        paths:
        - GameFiles.tar


Test:
  stage: test
  script:
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml
